apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx-httproute
  namespace: {{ .Values.namespace }}
spec:
  parentRefs:
  - name: nginx-gateway
    namespace: nginx-gw
  hostnames:
  - {{ .Values.gateway.hostname }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: nginx-app
      port: 80
